version: '2'
services:
  simpleDotNet-build:
    image: microsoft/aspnetcore-build:1.0.1
    volumes:
      - .:/sln
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /sln
    entrypoint: ["sh", "./buildme.sh"]